### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by FrenchTechLead** [phonegap/phonegap-template-react-hot-loader#12]
hello,
I have the following errors when i run npm start :

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle helloworld@1.0.0~prestart: helloworld@1.0.0
6 silly lifecycle helloworld@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle helloworld@1.0.0~start: helloworld@1.0.0
8 verbose lifecycle helloworld@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle helloworld@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\mecherim\PhoneGap projects\reactHotLoader\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Symantec\Symantec Endpoint Encryption Clients\;C:\Program Files\Git\cmd;C:\Program Files\apache-maven-3.3.9\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\Java\jdk1.8.0_121\jre\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\mecherim\AppData\Local\Android\sdk\tools;C:\Users\mecherim\AppData\Roaming\npm
10 verbose lifecycle helloworld@1.0.0~start: CWD: C:\Users\mecherim\PhoneGap projects\reactHotLoader
11 silly lifecycle helloworld@1.0.0~start: Args: [ '/d /s /c', 'node config && HOST=0.0.0.0 webpack-dev-server' ]
12 silly lifecycle helloworld@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle helloworld@1.0.0~start: Failed to exec start script
14 verbose stack Error: helloworld@1.0.0 start: `node config && HOST=0.0.0.0 webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid helloworld@1.0.0
16 verbose cwd C:\Users\mecherim\PhoneGap projects\reactHotLoader
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error helloworld@1.0.0 start: `node config && HOST=0.0.0.0 webpack-dev-server`
22 error Exit status 1
23 error Failed at the helloworld@1.0.0 start script 'node config && HOST=0.0.0.0 webpack-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the helloworld package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node config && HOST=0.0.0.0 webpack-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs helloworld
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls helloworld
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by FrenchTechLead** [comment]
Ok i just found this pull request that corrects it, it's an os compatibility  problem (windows):
https://github.com/phonegap/phonegap-template-react-hot-loader/pull/9
